
runtime: nodejs20
service: default

# Configures App Engine to serve static files directly
handlers:
  # Match specific file extensions and serve them directly
  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|tsx|ts|map))$
    static_files: \1
    upload: (.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|tsx|ts|map))$

  # Catch-all handler for SPA routing: serves index.html for any other route
  - url: /.*
    static_files: index.html
    upload: index.html
